/*
 * DotAAS Part 2 | HTTP/REST | Registry and Discovery
 * The registry and discovery interface as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.eclipse.basyx.aas.registry.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Endpoint
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-03T11:06:21.050Z[GMT]")
public class Endpoint {
  @SerializedName("interface")
  private String _interface = null;

  @SerializedName("protocolInformation")
  private ProtocolInformation protocolInformation = null;

  public Endpoint _interface(String _interface) {
    this._interface = _interface;
    return this;
  }

   /**
   * Get _interface
   * @return _interface
  **/
  @Schema(required = true, description = "")
  public String getInterface() {
    return _interface;
  }

  public void setInterface(String _interface) {
    this._interface = _interface;
  }

  public Endpoint protocolInformation(ProtocolInformation protocolInformation) {
    this.protocolInformation = protocolInformation;
    return this;
  }

   /**
   * Get protocolInformation
   * @return protocolInformation
  **/
  @Schema(required = true, description = "")
  public ProtocolInformation getProtocolInformation() {
    return protocolInformation;
  }

  public void setProtocolInformation(ProtocolInformation protocolInformation) {
    this.protocolInformation = protocolInformation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Endpoint endpoint = (Endpoint) o;
    return Objects.equals(this._interface, endpoint._interface) &&
        Objects.equals(this.protocolInformation, endpoint.protocolInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_interface, protocolInformation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Endpoint {\n");
    
    sb.append("    _interface: ").append(toIndentedString(_interface)).append("\n");
    sb.append("    protocolInformation: ").append(toIndentedString(protocolInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
