/*
 * DotAAS Part 2 | HTTP/REST | Registry and Discovery
 * The registry and discovery interface as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.eclipse.basyx.aas.registry.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets KeyType
 */
@JsonAdapter(KeyType.Adapter.class)
public enum KeyType {
  CUSTOM("Custom"),
  IRDI("IRDI"),
  IRI("IRI"),
  IDSHORT("IdShort"),
  FRAGMENTID("FragmentId");

  private String value;

  KeyType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static KeyType fromValue(String text) {
    for (KeyType b : KeyType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<KeyType> {
    @Override
    public void write(final JsonWriter jsonWriter, final KeyType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public KeyType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return KeyType.fromValue(String.valueOf(value));
    }
  }
}
