/*
 * DotAAS Part 2 | HTTP/REST | Registry and Discovery
 * The registry and discovery interface as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.eclipse.basyx.aas.registry.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ProtocolInformation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-03T11:06:21.050Z[GMT]")
public class ProtocolInformation {
  @SerializedName("endpointAddress")
  private String endpointAddress = null;

  @SerializedName("endpointProtocol")
  private String endpointProtocol = null;

  @SerializedName("endpointProtocolVersion")
  private String endpointProtocolVersion = null;

  @SerializedName("subprotocol")
  private String subprotocol = null;

  @SerializedName("subprotocolBody")
  private String subprotocolBody = null;

  @SerializedName("subprotocolBodyEncoding")
  private String subprotocolBodyEncoding = null;

  public ProtocolInformation endpointAddress(String endpointAddress) {
    this.endpointAddress = endpointAddress;
    return this;
  }

   /**
   * Get endpointAddress
   * @return endpointAddress
  **/
  @Schema(required = true, description = "")
  public String getEndpointAddress() {
    return endpointAddress;
  }

  public void setEndpointAddress(String endpointAddress) {
    this.endpointAddress = endpointAddress;
  }

  public ProtocolInformation endpointProtocol(String endpointProtocol) {
    this.endpointProtocol = endpointProtocol;
    return this;
  }

   /**
   * Get endpointProtocol
   * @return endpointProtocol
  **/
  @Schema(description = "")
  public String getEndpointProtocol() {
    return endpointProtocol;
  }

  public void setEndpointProtocol(String endpointProtocol) {
    this.endpointProtocol = endpointProtocol;
  }

  public ProtocolInformation endpointProtocolVersion(String endpointProtocolVersion) {
    this.endpointProtocolVersion = endpointProtocolVersion;
    return this;
  }

   /**
   * Get endpointProtocolVersion
   * @return endpointProtocolVersion
  **/
  @Schema(description = "")
  public String getEndpointProtocolVersion() {
    return endpointProtocolVersion;
  }

  public void setEndpointProtocolVersion(String endpointProtocolVersion) {
    this.endpointProtocolVersion = endpointProtocolVersion;
  }

  public ProtocolInformation subprotocol(String subprotocol) {
    this.subprotocol = subprotocol;
    return this;
  }

   /**
   * Get subprotocol
   * @return subprotocol
  **/
  @Schema(description = "")
  public String getSubprotocol() {
    return subprotocol;
  }

  public void setSubprotocol(String subprotocol) {
    this.subprotocol = subprotocol;
  }

  public ProtocolInformation subprotocolBody(String subprotocolBody) {
    this.subprotocolBody = subprotocolBody;
    return this;
  }

   /**
   * Get subprotocolBody
   * @return subprotocolBody
  **/
  @Schema(description = "")
  public String getSubprotocolBody() {
    return subprotocolBody;
  }

  public void setSubprotocolBody(String subprotocolBody) {
    this.subprotocolBody = subprotocolBody;
  }

  public ProtocolInformation subprotocolBodyEncoding(String subprotocolBodyEncoding) {
    this.subprotocolBodyEncoding = subprotocolBodyEncoding;
    return this;
  }

   /**
   * Get subprotocolBodyEncoding
   * @return subprotocolBodyEncoding
  **/
  @Schema(description = "")
  public String getSubprotocolBodyEncoding() {
    return subprotocolBodyEncoding;
  }

  public void setSubprotocolBodyEncoding(String subprotocolBodyEncoding) {
    this.subprotocolBodyEncoding = subprotocolBodyEncoding;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProtocolInformation protocolInformation = (ProtocolInformation) o;
    return Objects.equals(this.endpointAddress, protocolInformation.endpointAddress) &&
        Objects.equals(this.endpointProtocol, protocolInformation.endpointProtocol) &&
        Objects.equals(this.endpointProtocolVersion, protocolInformation.endpointProtocolVersion) &&
        Objects.equals(this.subprotocol, protocolInformation.subprotocol) &&
        Objects.equals(this.subprotocolBody, protocolInformation.subprotocolBody) &&
        Objects.equals(this.subprotocolBodyEncoding, protocolInformation.subprotocolBodyEncoding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointAddress, endpointProtocol, endpointProtocolVersion, subprotocol, subprotocolBody, subprotocolBodyEncoding);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProtocolInformation {\n");
    
    sb.append("    endpointAddress: ").append(toIndentedString(endpointAddress)).append("\n");
    sb.append("    endpointProtocol: ").append(toIndentedString(endpointProtocol)).append("\n");
    sb.append("    endpointProtocolVersion: ").append(toIndentedString(endpointProtocolVersion)).append("\n");
    sb.append("    subprotocol: ").append(toIndentedString(subprotocol)).append("\n");
    sb.append("    subprotocolBody: ").append(toIndentedString(subprotocolBody)).append("\n");
    sb.append("    subprotocolBodyEncoding: ").append(toIndentedString(subprotocolBodyEncoding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
