/*
 * DotAAS Part 2 | HTTP/REST | Registry and Discovery
 * The registry and discovery interface as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.eclipse.basyx.aas.registry.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * SubmodelDescriptor
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-03T11:06:21.050Z[GMT]")
public class SubmodelDescriptor extends Descriptor {
  @SerializedName("administration")
  private AdministrativeInformation administration = null;

  @SerializedName("description")
  private List<LangString> description = null;

  @SerializedName("idShort")
  private String idShort = null;

  @SerializedName("identification")
  private Identifier identification = null;

  @SerializedName("semanticId")
  private Reference semanticId = null;

  public SubmodelDescriptor administration(AdministrativeInformation administration) {
    this.administration = administration;
    return this;
  }

   /**
   * Get administration
   * @return administration
  **/
  @Schema(description = "")
  public AdministrativeInformation getAdministration() {
    return administration;
  }

  public void setAdministration(AdministrativeInformation administration) {
    this.administration = administration;
  }

  public SubmodelDescriptor description(List<LangString> description) {
    this.description = description;
    return this;
  }

  public SubmodelDescriptor addDescriptionItem(LangString descriptionItem) {
    if (this.description == null) {
      this.description = new ArrayList<LangString>();
    }
    this.description.add(descriptionItem);
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public List<LangString> getDescription() {
    return description;
  }

  public void setDescription(List<LangString> description) {
    this.description = description;
  }

  public SubmodelDescriptor idShort(String idShort) {
    this.idShort = idShort;
    return this;
  }

   /**
   * Get idShort
   * @return idShort
  **/
  @Schema(description = "")
  public String getIdShort() {
    return idShort;
  }

  public void setIdShort(String idShort) {
    this.idShort = idShort;
  }

  public SubmodelDescriptor identification(Identifier identification) {
    this.identification = identification;
    return this;
  }

   /**
   * Get identification
   * @return identification
  **/
  @Schema(required = true, description = "")
  public Identifier getIdentification() {
    return identification;
  }

  public void setIdentification(Identifier identification) {
    this.identification = identification;
  }

  public SubmodelDescriptor semanticId(Reference semanticId) {
    this.semanticId = semanticId;
    return this;
  }

   /**
   * Get semanticId
   * @return semanticId
  **/
  @Schema(description = "")
  public Reference getSemanticId() {
    return semanticId;
  }

  public void setSemanticId(Reference semanticId) {
    this.semanticId = semanticId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmodelDescriptor submodelDescriptor = (SubmodelDescriptor) o;
    return Objects.equals(this.administration, submodelDescriptor.administration) &&
        Objects.equals(this.description, submodelDescriptor.description) &&
        Objects.equals(this.idShort, submodelDescriptor.idShort) &&
        Objects.equals(this.identification, submodelDescriptor.identification) &&
        Objects.equals(this.semanticId, submodelDescriptor.semanticId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(administration, description, idShort, identification, semanticId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmodelDescriptor {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    administration: ").append(toIndentedString(administration)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    idShort: ").append(toIndentedString(idShort)).append("\n");
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    semanticId: ").append(toIndentedString(semanticId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
